version: '3.8'
services:

  app:
    # image: coba-up-docker-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/html